import { webToggleState } from "../../utils/accessibility";
import React, { useEffect, useState } from 'react';
import { Image, ImageBackground, Modal, Pressable, ScrollView, StyleSheet, useWindowDimensions, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { ChevronDown, Heart, Leaf, Pause, Play, RotateCcw, RotateCw, X } from 'lucide-react-native';
import Animated, { Easing, ReduceMotion, useAnimatedStyle, useSharedValue, withRepeat, withTiming } from 'react-native-reanimated';
import Svg, { Circle } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IconButton, T } from '../../components/ui';
import { useAppStore } from '../../store/useAppStore';
import { useTheme } from '../../theme';
import { SoundControls } from './SoundControls';
import { formatDuration } from '../../utils/analytics';

const format = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${Math.floor(seconds % 60).toString().padStart(2, '0')}`;

export function MeditationPlayer() {
  const session = useAppStore(s => s.activeSession); const expanded = useAppStore(s => s.playerExpanded); const playing = useAppStore(s => s.isPlaying); const elapsed = useAppStore(s => s.elapsed); const listened = useAppStore(s => s.listenedSeconds); const favorites = useAppStore(s => s.favorites);
  const togglePlaying = useAppStore(s => s.togglePlaying); const setExpanded = useAppStore(s => s.setPlayerExpanded); const setElapsed = useAppStore(s => s.setElapsed); const toggleFavorite = useAppStore(s => s.toggleFavorite); const finishSession = useAppStore(s => s.finishSession);
  const [confirmEnd, setConfirmEnd] = useState(false); const { width } = useWindowDimensions(); const insets = useSafeAreaInsets(); const mobile = width < 600;
  const scale = useSharedValue(1);
  useEffect(() => { scale.set(playing ? withRepeat(withTiming(1.06, { duration: 4000, easing: Easing.inOut(Easing.sin), reduceMotion: ReduceMotion.System }), -1, true) : withTiming(1, { duration: 600 })); }, [playing, scale]);
  const animated = useAnimatedStyle(() => ({ transform: [{ scale: scale.get() }] }));
  if (!session) return null;
  const total = session.duration * 60; const progress = elapsed / total; const ringSize = mobile ? 205 : 235; const radius = (ringSize - 5) / 2; const circumference = radius * 2 * Math.PI; const breath = elapsed % 16 < 4 ? 'Breathe in' : elapsed % 16 < 8 ? 'Hold gently' : elapsed % 16 < 12 ? 'Breathe out' : 'Rest here';
  return <Modal visible={expanded} animationType="slide" onRequestClose={() => setExpanded(false)} statusBarTranslucent><ImageBackground source={session.image} blurRadius={15} style={{ flex: 1, backgroundColor: '#1E342B' }}><LinearGradient colors={['rgba(17,35,29,.83)', 'rgba(22,42,31,.87)', 'rgba(18,36,29,.98)']} style={StyleSheet.absoluteFill}/><View style={{ paddingTop: insets.top + 18, paddingHorizontal: mobile ? 20 : 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Pressable accessibilityRole="button" accessibilityLabel="Minimize meditation player" onPress={() => setExpanded(false)} style={{ minWidth: 44, minHeight: 44, flexDirection: 'row', gap: 8, alignItems: 'center' }}><ChevronDown size={23} color="#E0E8D8"/>{!mobile && <T size={12} color="#C4D0BE">Back to your space</T>}</Pressable><View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Leaf color="#B7CBA5" size={16}/><T size={9} color="#D6E2CF" style={{ letterSpacing: 1.7 }}>A MOMENT OF STILLNESS</T></View><Pressable accessibilityRole="button" accessibilityLabel="Save this meditation" accessibilityState={{ selected: favorites.includes(session.id) }} {...webToggleState(favorites.includes(session.id))} onPress={() => toggleFavorite(session.id)} style={{ width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }}><Heart size={21} color="#DDE5D7" fill={favorites.includes(session.id) ? '#DDE5D7' : 'none'}/></Pressable></View>
    <ScrollView contentContainerStyle={{ flexGrow: 1, alignItems: 'center', paddingHorizontal: 22, paddingTop: mobile ? 24 : 16, paddingBottom: 26 + insets.bottom }}>
      <T size={10} color="#AFC2A4" weight="medium" style={{ letterSpacing: 2, textTransform: 'uppercase' }}>{session.category} · {session.duration} minutes</T><T size={mobile ? 26 : 32} weight="display" color="#F7F8F2" style={{ marginTop: 8, textAlign: 'center', letterSpacing: -0.5 }}>{session.title}</T><T size={12} color="#B6C7AE" style={{ marginTop: 7 }}>Your time to pause, breathe, and just be.</T>
      <View style={{ marginTop: 30, marginBottom: 24, width: ringSize, height: ringSize, alignItems: 'center', justifyContent: 'center' }}><Animated.View style={[{ width: ringSize - 30, height: ringSize - 30, borderRadius: ringSize, overflow: 'hidden', backgroundColor: '#3D5341' }, animated]}><Image source={session.image} style={{ width: '100%', height: '100%', opacity: 0.7 }}/><View style={[StyleSheet.absoluteFill, { backgroundColor: '#243B2850', justifyContent: 'center', alignItems: 'center' }]}><T size={16} color="#FFFFFF" weight="display">{playing ? breath : 'Stay a little while'}</T><T size={9} color="#D7E1CC" style={{ marginTop: 6, letterSpacing: 1.5 }}>{playing ? 'JUST AS YOU ARE' : 'PAUSED'}</T></View></Animated.View><Svg width={ringSize} height={ringSize} style={StyleSheet.absoluteFill}><Circle cx={ringSize/2} cy={ringSize/2} r={radius} stroke="#FFFFFF20" strokeWidth={3} fill="none"/><Circle cx={ringSize/2} cy={ringSize/2} r={radius} stroke="#C5D6B5" strokeWidth={3} strokeLinecap="round" strokeDasharray={`${circumference} ${circumference}`} strokeDashoffset={circumference * (1 - progress)} fill="none" transform={`rotate(-90 ${ringSize/2} ${ringSize/2})`}/></Svg></View>
      <T size={30} weight="medium" color="#F6F8F1" style={{ letterSpacing: 1, lineHeight: 39, fontVariant: ['tabular-nums'] }}>{format(total - elapsed)}</T><T size={10} color="#AFC0A6" style={{ marginTop: 3 }}>of {format(total)} · remaining</T>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 36, marginTop: 22 }}><Pressable accessibilityRole="button" accessibilityLabel="Rewind 15 seconds" onPress={() => setElapsed(elapsed - 15)} style={styles.skip}><RotateCcw size={24} color="#DAE4D1"/><T size={8} color="#DAE4D1" style={{ position: 'absolute', top: 20 }}>15</T></Pressable><Pressable accessibilityRole="button" accessibilityLabel={playing ? 'Pause meditation' : 'Resume meditation'} onPress={togglePlaying} style={({ pressed }) => ({ width: 64, height: 64, borderRadius: 32, backgroundColor: '#E8EEDC', alignItems: 'center', justifyContent: 'center', opacity: pressed ? 0.8 : 1 })}>{playing ? <Pause size={23} color="#35543D" fill="#35543D"/> : <Play size={23} color="#35543D" fill="#35543D"/>}</Pressable><Pressable accessibilityRole="button" accessibilityLabel="Skip forward 15 seconds" onPress={() => setElapsed(elapsed + 15)} style={styles.skip}><RotateCw size={24} color="#DAE4D1"/><T size={8} color="#DAE4D1" style={{ position: 'absolute', top: 20 }}>15</T></Pressable></View>
      <SoundControls onFinish={() => setConfirmEnd(true)}/>
    </ScrollView>
    {confirmEnd && <View style={[StyleSheet.absoluteFill, { alignItems: 'center', justifyContent: 'center', backgroundColor: '#102218C9', padding: 24 }]}><View style={{ width: '100%', maxWidth: 380, padding: 30, borderRadius: 22, backgroundColor: '#F6F7EF', alignItems: 'center' }}><Leaf color="#59784C" size={28}/><T size={23} weight="display" color="#2E4432" style={{ marginTop: 15, textAlign: 'center' }}>Carry a little calm with you.</T><T size={12} color="#7A8573" style={{ textAlign: 'center', marginTop: 10, lineHeight: 21 }}>{listened > 0 ? `${formatDuration(listened / 60)} of actual practice is saved on this device. Your daily progress is already up to date.` : 'Come back whenever you are ready. Your practice will be saved as you listen.'}</T><Pressable accessibilityRole="button" onPress={() => { setConfirmEnd(false); finishSession(); }} style={{ width: '100%', backgroundColor: '#4E7257', padding: 14, borderRadius: 11, alignItems: 'center', marginTop: 23 }}><T size={12} color="#FFFFFF" weight="semibold">Finish this moment</T></Pressable><Pressable accessibilityRole="button" onPress={() => setConfirmEnd(false)} style={{ padding: 16 }}><T size={12} color="#59784C">Stay a little longer</T></Pressable></View></View>}
  </ImageBackground></Modal>;
}
export function MiniPlayer({ mobile }: { mobile: boolean }) {
  const t = useTheme(); const session = useAppStore(s => s.activeSession); const expanded = useAppStore(s => s.playerExpanded); const playing = useAppStore(s => s.isPlaying); const elapsed = useAppStore(s => s.elapsed); const setExpanded = useAppStore(s => s.setPlayerExpanded); const togglePlaying = useAppStore(s => s.togglePlaying); const closePlayer = useAppStore(s => s.closePlayer); const insets = useSafeAreaInsets();
  if (!session || expanded) return null;
  return <View style={{ position: 'absolute', bottom: mobile ? 67 + insets.bottom : 20, left: mobile ? 12 : 30, right: mobile ? 12 : 30, maxWidth: 850, alignSelf: 'center', backgroundColor: t.surface, borderRadius: 14, borderWidth: 1, borderColor: t.border, overflow: 'hidden', boxShadow: '0 5px 35px rgba(20,40,20,0.13)' }}><View style={{ flexDirection: 'row', gap: 12, padding: 11, alignItems: 'center' }}><Pressable accessibilityRole="button" accessibilityLabel="Expand meditation player" onPress={() => setExpanded(true)} style={{ flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 }}><Image source={session.image} style={{ width: 43, height: 43, borderRadius: 9 }}/><View style={{ flex: 1 }}><T size={12} weight="semibold">{session.title}</T><T size={10} color={t.secondary}>{playing ? 'A little time for you' : 'Paused'} · {format(session.duration * 60 - elapsed)} left</T></View></Pressable><IconButton icon={playing ? Pause : Play} label={playing ? 'Pause meditation' : 'Resume meditation'} onPress={togglePlaying} size={20} color={t.primary}/><IconButton icon={X} label="Close meditation player" onPress={closePlayer} size={16}/></View><View style={{ height: 3, backgroundColor: t.primarySoft }}><View style={{ height: 3, backgroundColor: t.primary, width: `${elapsed / (session.duration * 60) * 100}%` }}/></View></View>;
}
const styles = StyleSheet.create({ skip: { height: 50, width: 50, alignItems: 'center', justifyContent: 'center' } });
