import { webToggleState } from "../../utils/accessibility";
import React, { useState } from 'react';
import { Pressable, View } from 'react-native';
import { CloudRain, Flame, Minus, Plus, Timer, Trees, Volume2, VolumeX, Waves, Wind } from 'lucide-react-native';
import { T } from '../../components/ui';
import { useAppStore } from '../../store/useAppStore';

const sounds = [{ label: 'Rain', icon: CloudRain }, { label: 'Ocean', icon: Waves }, { label: 'Forest', icon: Trees }, { label: 'Wind', icon: Wind }, { label: 'Fireplace', icon: Flame }, { label: 'White noise', icon: Wind }];
export function SoundControls({ onFinish }: { onFinish: () => void }) {
  const [showTimer, setShowTimer] = useState(false);
  const sound = useAppStore(s => s.backgroundSound); const volume = useAppStore(s => s.volume); const timer = useAppStore(s => s.sleepTimer); const setSound = useAppStore(s => s.setBackgroundSound); const setVolume = useAppStore(s => s.setVolume); const setTimer = useAppStore(s => s.setSleepTimer);
  return <><View style={{ width: '100%', maxWidth: 520, marginTop: 30, paddingTop: 22, borderTopWidth: 1, borderTopColor: '#FFFFFF16', alignItems: 'center' }}><T size={9} color="#AFC0A6" style={{ letterSpacing: 1.6 }}>SET THE SCENE</T><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%', marginTop: 17 }}>{sounds.map(s => <Pressable key={s.label} accessibilityRole="button" accessibilityLabel={`${s.label} ambient sound`} accessibilityState={{ selected: sound === s.label }} {...webToggleState(sound === s.label)} onPress={() => setSound(s.label)} style={{ alignItems: 'center', gap: 7, flex: 1 }}><View style={{ height: 41, width: 41, borderRadius: 13, backgroundColor: sound === s.label ? '#BDCFAC30' : '#FFFFFF08', borderWidth: 1, borderColor: sound === s.label ? '#BDCFAC88' : '#FFFFFF12', alignItems: 'center', justifyContent: 'center' }}><s.icon size={19} color={sound === s.label ? '#E5EDD9' : '#95A88D'} strokeWidth={1.5}/></View><T size={8} color={sound === s.label ? '#DEE7D3' : '#95A88D'}>{s.label}</T></Pressable>)}</View>
    <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 11, marginTop: 22 }}><Pressable accessibilityRole="button" accessibilityLabel="Decrease volume" onPress={() => setVolume(Math.max(0, volume - .1))} style={{ minHeight: 40, minWidth: 35, alignItems: 'center', justifyContent: 'center' }}><Minus size={14} color="#BDCFAD"/></Pressable>{volume === 0 ? <VolumeX size={17} color="#B7C7AC"/> : <Volume2 size={17} color="#B7C7AC"/>}<Pressable accessibilityRole="adjustable" accessibilityLabel="Ambient volume" accessibilityValue={{ min: 0, max: 100, now: Math.round(volume * 100), text: `${Math.round(volume * 100)} percent` }} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(volume * 100)} aria-valuetext={`${Math.round(volume * 100)} percent`} onPress={e => setVolume(Math.max(0, Math.min(1, e.nativeEvent.locationX / 150)))} style={{ width: 150, height: 40, justifyContent: 'center' }}><View style={{ height: 3, backgroundColor: '#FFFFFF25', borderRadius: 4 }}><View style={{ width: `${volume * 100}%`, height: 3, backgroundColor: '#BECFAC', borderRadius: 4 }}/><View style={{ position: 'absolute', left: `${volume * 100}%`, marginLeft: -5, top: -3.5, width: 10, height: 10, borderRadius: 5, backgroundColor: '#E6EEDB' }}/></View></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Increase volume" onPress={() => setVolume(Math.min(1, volume + .1))} style={{ minHeight: 40, minWidth: 35, alignItems: 'center', justifyContent: 'center' }}><Plus size={14} color="#BDCFAD"/></Pressable></View></View>
    <View style={{ flexDirection: 'row', gap: 24, alignItems: 'center', marginTop: 9 }}><Pressable accessibilityRole="button" accessibilityState={{ expanded: showTimer }} aria-expanded={showTimer} onPress={() => setShowTimer(!showTimer)} style={{ flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 44 }}><Timer size={15} color="#9FB095"/><T size={11} color="#B6C6AB">{timer ? `${timer} min sleep timer` : 'Sleep timer'}</T></Pressable><View style={{ height: 12, width: 1, backgroundColor: '#FFFFFF25' }}/><Pressable accessibilityRole="button" onPress={onFinish} style={{ minHeight: 44, justifyContent: 'center' }}><T size={11} color="#B6C6AB">Finish practice</T></Pressable></View>
    {showTimer && <View style={{ flexDirection: 'row', gap: 7, flexWrap: 'wrap', justifyContent: 'center', marginTop: 8 }}>{[10, 20, 30, 45, 60, null].map(value => <Pressable key={String(value)} accessibilityRole="button" accessibilityState={{ selected: timer === value }} {...webToggleState(timer === value)} onPress={() => { setTimer(value); setShowTimer(false); }} style={{ paddingHorizontal: 12, paddingVertical: 9, borderRadius: 8, backgroundColor: timer === value ? '#BDCFAC40' : '#FFFFFF12' }}><T size={10} color="#E0E9D5">{value ? `${value} min` : 'End of session'}</T></Pressable>)}</View>}
    <T size={9} color="#829679" style={{ marginTop: 10 }}>Ambient sound practice · Original audio, available offline</T>
  </>;
}
